/*
 * Copyright (c) 2020 VMware, Inc
 *
 *  SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.catalog;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/** PolicyStats */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2020-09-09T18:27:41.063635-04:00[America/New_York]")
public class PolicyStats {
  @SerializedName("conflictCount")
  private Long conflictCount = null;

  @SerializedName("enforcedCount")
  private Long enforcedCount = null;

  @SerializedName("notEnforcedCount")
  private Long notEnforcedCount = null;

  public PolicyStats conflictCount(Long conflictCount) {
    this.conflictCount = conflictCount;
    return this;
  }

  /**
   * Get conflictCount
   *
   * @return conflictCount
   */
  @Schema(description = "")
  public Long getConflictCount() {
    return conflictCount;
  }

  public void setConflictCount(Long conflictCount) {
    this.conflictCount = conflictCount;
  }

  public PolicyStats enforcedCount(Long enforcedCount) {
    this.enforcedCount = enforcedCount;
    return this;
  }

  /**
   * Get enforcedCount
   *
   * @return enforcedCount
   */
  @Schema(description = "")
  public Long getEnforcedCount() {
    return enforcedCount;
  }

  public void setEnforcedCount(Long enforcedCount) {
    this.enforcedCount = enforcedCount;
  }

  public PolicyStats notEnforcedCount(Long notEnforcedCount) {
    this.notEnforcedCount = notEnforcedCount;
    return this;
  }

  /**
   * Get notEnforcedCount
   *
   * @return notEnforcedCount
   */
  @Schema(description = "")
  public Long getNotEnforcedCount() {
    return notEnforcedCount;
  }

  public void setNotEnforcedCount(Long notEnforcedCount) {
    this.notEnforcedCount = notEnforcedCount;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyStats policyStats = (PolicyStats) o;
    return Objects.equals(this.conflictCount, policyStats.conflictCount)
        && Objects.equals(this.enforcedCount, policyStats.enforcedCount)
        && Objects.equals(this.notEnforcedCount, policyStats.notEnforcedCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conflictCount, enforcedCount, notEnforcedCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyStats {\n");

    sb.append("    conflictCount: ").append(toIndentedString(conflictCount)).append("\n");
    sb.append("    enforcedCount: ").append(toIndentedString(enforcedCount)).append("\n");
    sb.append("    notEnforcedCount: ").append(toIndentedString(notEnforcedCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
