/*
 * Copyright (c) 2020 VMware, Inc
 *
 *  SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.catalog;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/** A resource part of a deployment. */
@Schema(description = "A resource part of a deployment.")
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2020-09-09T18:27:41.063635-04:00[America/New_York]")
public class Resource {
  @SerializedName("createdAt")
  private Date createdAt = null;

  @SerializedName("dependsOn")
  private List<String> dependsOn = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("expense")
  private Expense expense = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("properties")
  private Object properties = null;

  /** The current state of the resource */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    PARTIAL("PARTIAL"),
    TAINTED("TAINTED"),
    OK("OK");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration)
          throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StateEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  /** The current sync status */
  @JsonAdapter(SyncStatusEnum.Adapter.class)
  public enum SyncStatusEnum {
    SUCCESS("SUCCESS"),
    MISSING("MISSING"),
    STALE("STALE");

    private String value;

    SyncStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SyncStatusEnum fromValue(String text) {
      for (SyncStatusEnum b : SyncStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SyncStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SyncStatusEnum enumeration)
          throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SyncStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SyncStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("syncStatus")
  private SyncStatusEnum syncStatus = null;

  @SerializedName("type")
  private String type = null;

  public Resource createdAt(Date createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Creation time
   *
   * @return createdAt
   */
  @Schema(description = "Creation time")
  public Date getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  public Resource dependsOn(List<String> dependsOn) {
    this.dependsOn = dependsOn;
    return this;
  }

  public Resource addDependsOnItem(String dependsOnItem) {
    if (this.dependsOn == null) {
      this.dependsOn = new ArrayList<String>();
    }
    this.dependsOn.add(dependsOnItem);
    return this;
  }

  /**
   * A list of other resources this resource depends on
   *
   * @return dependsOn
   */
  @Schema(description = "A list of other resources this resource depends on")
  public List<String> getDependsOn() {
    return dependsOn;
  }

  public void setDependsOn(List<String> dependsOn) {
    this.dependsOn = dependsOn;
  }

  public Resource description(String description) {
    this.description = description;
    return this;
  }

  /**
   * A description of the resource
   *
   * @return description
   */
  @Schema(description = "A description of the resource")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Resource expense(Expense expense) {
    this.expense = expense;
    return this;
  }

  /**
   * Get expense
   *
   * @return expense
   */
  @Schema(description = "")
  public Expense getExpense() {
    return expense;
  }

  public void setExpense(Expense expense) {
    this.expense = expense;
  }

  public Resource id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the resource
   *
   * @return id
   */
  @Schema(description = "Unique identifier of the resource")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Resource name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the resource
   *
   * @return name
   */
  @Schema(required = true, description = "Name of the resource")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Resource properties(Object properties) {
    this.properties = properties;
    return this;
  }

  /**
   * Get properties
   *
   * @return properties
   */
  @Schema(description = "")
  public Object getProperties() {
    return properties;
  }

  public void setProperties(Object properties) {
    this.properties = properties;
  }

  public Resource state(StateEnum state) {
    this.state = state;
    return this;
  }

  /**
   * The current state of the resource
   *
   * @return state
   */
  @Schema(description = "The current state of the resource")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public Resource syncStatus(SyncStatusEnum syncStatus) {
    this.syncStatus = syncStatus;
    return this;
  }

  /**
   * The current sync status
   *
   * @return syncStatus
   */
  @Schema(description = "The current sync status")
  public SyncStatusEnum getSyncStatus() {
    return syncStatus;
  }

  public void setSyncStatus(SyncStatusEnum syncStatus) {
    this.syncStatus = syncStatus;
  }

  public Resource type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Type of the resource
   *
   * @return type
   */
  @Schema(required = true, description = "Type of the resource")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resource resource = (Resource) o;
    return Objects.equals(this.createdAt, resource.createdAt)
        && Objects.equals(this.dependsOn, resource.dependsOn)
        && Objects.equals(this.description, resource.description)
        && Objects.equals(this.expense, resource.expense)
        && Objects.equals(this.id, resource.id)
        && Objects.equals(this.name, resource.name)
        && Objects.equals(this.properties, resource.properties)
        && Objects.equals(this.state, resource.state)
        && Objects.equals(this.syncStatus, resource.syncStatus)
        && Objects.equals(this.type, resource.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        createdAt, dependsOn, description, expense, id, name, properties, state, syncStatus, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resource {\n");

    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    dependsOn: ").append(toIndentedString(dependsOn)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expense: ").append(toIndentedString(expense)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    syncStatus: ").append(toIndentedString(syncStatus)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
